version: '1'

services:
  client:
    container_name: peepo-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
